title: Yingjie Niu's Homepage
page-top-title: Yingjie Niu
top-section-bg-text: Computer Science
home-subtitle: Yingjie Niu&ensp;|&ensp;牛英杰
copyright-text: '&copy; Yingjie Niu 2024-2025. All Rights Reserved.'
